### ISSUE TITLE
README is sometimes false, and is missing information to correct the fallacy

### ISSUE THREAD

**Issue by brandonzylstra** [ReturnInfinity/BareMetal-lwIP#4]
The README states that 

> This web page you are reading was served by a simple web server running on top of the lightweight TCP/IP stack lwIP, which in turn is running on top of BareMetal.

Since I'm reading that text on GitHub, and I'm pretty sure that GitHub is not being served by IwIP on top of BareMetal, the statement is (in this context!) false.  I assume that it is true when read in the context of the web site you've set up for the project, but there's no link in the README or in the project metadata to take me there.

I would propose listing the correct URI for the project site in GitHub project metadata (where project links normally go) and amending the text of the README slightly so that it is true even when read on GitHub.

**Comment by brandonzylstra** [comment]
I googled for the project site, but only found the GitHub page.  (Results may include more than GitHub in the future, but at the moment that's the only thing you get from this link.)

https://www.google.com/?gws_rd=ssl#newwindow=1&q=%22This+web+page+you+are+reading+was+served+by+a+simple+web+server+running+on+top+of+the+lightweight+TCP%2FIP+stack+lwIP%2C+which+in+turn+is+running+on+top+of+BareMetal%22

**Comment by IanSeyler** [comment]
You are correct. I just copy/pasted the example page into the README. Will correct this soon!

**Comment by brandonzylstra** [comment]
Where _is_ the example page?  I couldn't find it anywhere.

On Fri, Oct 31, 2014 at 1:29 PM, Ian Seyler notifications@github.com
wrote:

> Closed #4 https://github.com/ReturnInfinity/BareMetal-lwIP/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ReturnInfinity/BareMetal-lwIP/issues/4#event-186698067
> .

## 

Brandon Zylstra
brandon.zylstra@gmail.com

**Comment by IanSeyler** [comment]
It's in httpd_raw/fs/

I added some instructions to the README about rebuilding the page. The content in httpd_raw/fs/ gets transcribed to httpd_raw/fsdata.c
